### ISSUE TITLE
Doesn't work with pip 10

### ISSUE THREAD

**Issue by jmbowman** [signalpillar/tox-battery#14]
pip 10 was recently released, making some backwards-incompatible changes to internal APIs that tox-battery uses:

```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 39, in main
    config = prepare(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/session.py", line 27, in prepare
    config = parseconfig(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 205, in parseconfig
    pm = get_plugin_manager(plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/tox/config.py", line 44, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/toxbat/requirements.py", line 38, in <module>
    from pip.download import PipSession
ImportError: No module named download
```

pip-tools got around this by vendoring a copy of pip: https://github.com/jazzband/pip-tools/issues/580

**Comment by signalpillar** [comment]
Hi, @jmbowman thank you for reporting the issue. I also noticed today that failure.

**Comment by signalpillar** [comment]
The plug-in supported one version of pip internals so now it supports the other. 
https://github.com/signalpillar/tox-battery/pull/15
