### ISSUE TITLE
pip 20.1 causes internal error

### ISSUE THREAD

**Issue by nedbat** [signalpillar/tox-battery#23]
Looks like pip broke tox-battery again:
```
Traceback (most recent call last):
  File "c:\python27-x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27-x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27-x64\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "c:\python27-x64\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\python27-x64\lib\site-packages\tox\session\__init__.py", line 64, in main
    config = load_config(args)
  File "c:\python27-x64\lib\site-packages\tox\session\__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "c:\python27-x64\lib\site-packages\tox\config\__init__.py", line 267, in parseconfig
    pm.hook.tox_configure(config=config)  # post process config object
  File "c:\python27-x64\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python27-x64\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python27-x64\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python27-x64\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\python27-x64\lib\site-packages\pluggy\callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "c:\python27-x64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 60, in tox_configure
    return _ensure_envs_recreated_on_requirements_update(config)
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 72, in _ensure_envs_recreated_on_requirements_update
    requires_recreation = are_requirements_changed(env)
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 96, in are_requirements_changed
    if reqfile and os.path.isfile(reqfile)])
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 126, in is_changed
    new_requirements = parse_pip_requirements(fpath)
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 109, in parse_pip_requirements
    session=PipSession())
  File "c:\python27-x64\lib\site-packages\toxbat\requirements.py", line 110, in <genexpr>
    if r.req
AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

**Comment by signalpillar** [comment]
@feanil fixed the issue by removing dependency on PIP
